// The Java that Driver Config writes into a robot project, and the only way it ever edits one.
//
// The file has two marked regions - its imports, and the body of the class - and the app rewrites
// those and nothing else. Everything outside them is the team's: a package line they moved, a helper
// they added, a comment. The regions are replaced by character offset, so the bytes outside them are
// not even re-joined, let alone reformatted.
//
// The profile itself travels inside the body region as a JSON block comment. That is what the app
// reads back, and regenerating from it and comparing is how the app notices a hand edit inside a
// region before overwriting it.
//
// Library API used, all of it present at FrcCatalyst 5adc688b (2.0.0-alpha.3) and unchanged in
// 2.0.0-beta.1: DriverProfile (builder, Curve, apply, engage/disengageSlowMode), RumbleEvents
// (onTrigger, update, clear, Pattern, Channel), SlewRateLimiter, Commands.startEnd, CatalystLog.log,
// RobotState.isDisabled / lateMatch / lowBattery / enabled / teleop / autonomous and
// RobotSafety.trippedTrigger. From WPILib, only what exists in both alpha-6 and alpha-7:
// CommandGenericHID, Trigger, GenericHID.getSupportedOutputs, DriverStationErrors and plain
// NetworkTables topics. SendableChooser is deliberately not used - alpha-7 removed it.

import { CURVES, LIBRARY, POV_METHOD, RUMBLE_PATTERNS, STATIC_EVENTS, WHEN, javaNumber } from "./catalog.js";
import {
  DRIVE_ROLES, SAFE_ACTION, SAFE_EVENT, actionLabel, capsFor, eventLabel, inputLabel, isMeasured,
  layoutOf, normalize, parseConfig, refusal, roleLabel, serializeConfig,
} from "./model.js";

/** Bumped whenever the generated Java changes shape, so an older file is not mistaken for a hand edit. */
export const GENERATOR = 1;

export const MARK = {
  importsBegin: "// >>> CATALYST DRIVER CONFIG: IMPORTS (generated by CatalystApp - edit in the app, not here)",
  importsEnd: "// <<< CATALYST DRIVER CONFIG: IMPORTS",
  bodyBegin: "// >>> CATALYST DRIVER CONFIG: BODY (generated by CatalystApp Driver Config - edit it in the app; changes here are overwritten)",
  bodyEnd: "// <<< CATALYST DRIVER CONFIG: BODY",
  constantsBegin: "// >>> CATALYST DRIVER CONFIG: CONSTANTS (generated by CatalystApp Driver Config - edit it in the app; changes here are overwritten)",
  constantsEnd: "// <<< CATALYST DRIVER CONFIG: CONSTANTS",
};
const BEGIN_RE = /^([ \t]*)\/\/ >>> CATALYST DRIVER CONFIG: (IMPORTS|BODY|CONSTANTS)\b/;
const END_RE = /^[ \t]*\/\/ <<< CATALYST DRIVER CONFIG: (IMPORTS|BODY|CONSTANTS)\b/;
const JSON_BEGIN = "/* catalyst-driver-config";

// ------------------------------------------------------------------ safe text

const hex4 = (n) => n.toString(16).padStart(4, "0");

/**
 * A Java string literal. Non-ASCII becomes \uXXXX and control characters octal escapes: javac
 * translates \u escapes before it lexes, so emitting one for a quote or a newline would end the
 * literal early. Only characters above 0x7E are ever written that way.
 */
export function javaString(s) {
  let out = "\"";
  for (const ch of String(s)) {
    const c = ch.codePointAt(0);
    if (ch === "\"") out += "\\\"";
    else if (ch === "\\") out += "\\\\";
    else if (ch === "\n") out += "\\n";
    else if (ch === "\r") out += "\\r";
    else if (ch === "\t") out += "\\t";
    else if (c < 0x20 || c === 0x7f) out += "\\" + c.toString(8).padStart(3, "0");
    else if (c > 0x7e) {
      for (let k = 0; k < ch.length; k++) out += "\\u" + hex4(ch.charCodeAt(k));
    } else out += ch;
  }
  return out + "\"";
}

/**
 * Text that is safe inside a Java comment. Backslashes are doubled first, so a name that happens
 * to contain a backslash-u escape for a line feed cannot become a line break in javac's eyes and
 * turn the rest of a comment into code; then non-ASCII becomes an escape javac reads back as the same character.
 */
export function commentSafe(s) {
  return String(s)
    .replace(/\\/g, "\\\\")
    .replace(/[\r\n]+/g, " ")
    .replace(/\*\//g, "*\\/")
    .replace(/[^\x20-\x7e]/g, (ch) => "\\u" + hex4(ch.charCodeAt(0)));
}

/** The profile as the lines of the JSON block comment, pure ASCII and unable to close the comment. */
export function embeddedJson(config) {
  return serializeConfig(config)
    .replace(/\*\//g, "*\\/")
    .replace(/[^\x00-\x7e]/g, (ch) => "\\u" + hex4(ch.charCodeAt(0)))
    .split("\n");
}

// ------------------------------------------------------------------ generation

function importLines() {
  return [
    "import frc.lib.catalyst.command.CatalystCommand;",
    "import frc.lib.catalyst.command.Commands;",
    "import frc.lib.catalyst.logging.CatalystLog;",
    "import frc.lib.catalyst.util.AllianceFlipUtil;",
    "import frc.lib.catalyst.util.DriverProfile;",
    "import frc.lib.catalyst.util.RumbleEvents;",
    "import frc.lib.catalyst.util.SlewRateLimiter;",
    "import java.util.HashSet;",
    "import java.util.Set;",
    "import java.util.function.DoubleSupplier;",
    "import org.wpilib.command3.Trigger;",
    "import org.wpilib.command3.button.CommandGenericHID;",
    "import org.wpilib.driverstation.DriverStationErrors;",
    "import org.wpilib.driverstation.GenericHID;",
    "import org.wpilib.math.geometry.Pose2d;",
    "import org.wpilib.math.geometry.Rotation2d;",
    "import org.wpilib.networktables.NetworkTableInstance;",
    "import org.wpilib.networktables.StringArrayPublisher;",
    "import org.wpilib.networktables.StringPublisher;",
    "import org.wpilib.networktables.StringSubscriber;",
  ];
}

export function importsBlock(config) {
  normalize(config);
  return [MARK.importsBegin, ...importLines(), MARK.importsEnd];
}

function inputExpr(input) {
  if (input.kind === "button") return `p.controller.button(${input.index})`;
  if (input.kind === "pov") {
    if (!POV_METHOD[input.dir]) throw new Error(`not a D-pad direction: ${input.dir}`);
    return `p.controller.${POV_METHOD[input.dir]}()`;
  }
  if (input.kind === "axis") return `p.controller.axisGreaterThan(${input.index}, ${javaNumber(input.threshold)})`;
  throw new Error(`not an input: ${JSON.stringify(input)}`);
}

function actionExpr(action, hasRobot, swerve) {
  if (action.kind === "builtin" && action.id === "reseed") {
    if (!hasRobot || !swerve) throw new Error("Reseed heading needs the robot's SwerveSubsystem");
    return "Commands.runOnce(this::reseedHeading).withName(\"Driver Config: reseed heading\")";
  }
  if (action.kind === "builtin") {
    const field = action.id === "slow" ? "slowHeld" : action.id === "turbo" ? "turboHeld" : null;
    if (!field) throw new Error(`not a Driver Config action: ${action.id}`);
    return `Commands.startEnd(() -> ${field} = true, () -> ${field} = false).withName(${javaString(`Driver Config: ${action.id === "slow" ? "slow mode" : "turbo"}`)})`;
  }
  if (!SAFE_ACTION.test(action.expr)) throw new Error(`refusing to generate "${action.expr}": not an action this tool writes`);
  if (refusal(action.expr)) throw new Error(`refusing to generate "${action.expr}": ${refusal(action.expr)}`);
  if (!hasRobot) throw new Error(`"${action.expr}" needs a robot class`);
  return action.expr;
}

function eventExpr(event, hasRobot) {
  if (event.kind === "builtin") {
    if (event.id === "slow") return "new Trigger(() -> slowHeld)";
    if (event.id === "turbo") return "new Trigger(() -> turboHeld && !slowHeld)";
    throw new Error(`not a Driver Config event: ${event.id}`);
  }
  if (event.kind === "static") {
    const s = STATIC_EVENTS[event.id];
    if (!s) throw new Error(`not a library event: ${event.id}`);
    return s.java(event.param);
  }
  if (event.kind === "input") return inputExpr(event.input);
  if (!SAFE_EVENT.test(event.expr)) throw new Error(`refusing to generate "${event.expr}": not an event this tool writes`);
  if (!hasRobot) throw new Error(`"${event.expr}" needs a robot class`);
  return event.expr;
}

function axisExpr(a, speed) {
  const isDrive = DRIVE_ROLES.includes(a.role);
  const caps = capsFor(a, speed, isDrive);
  const curve = CURVES[a.curve];
  if (!curve) throw new Error(`not a curve: ${a.curve}`);
  return `new Axis(${javaString(a.role)}, ${a.axis}, ${a.invert}, ${javaNumber(a.deadband)}, DriverProfile.Curve.${curve.java}, ` +
    `${javaNumber(caps.normal)}, ${javaNumber(isDrive ? speed.slow : 1)}, ${javaNumber(caps.turbo)}, ${javaNumber(a.slew)})`;
}

/** The body region's lines, without the marker lines and without the class's indentation. */
function bodyLines(c) {
  const t = c.target;
  const hasRobot = !!t.robotClass;
  const cls = t.className;
  const L = [];
  const blank = () => L.push("");

  L.push(JSON_BEGIN);
  for (const line of embeddedJson(c)) L.push(" * " + line);
  L.push(" */");
  L.push(`// Generator: CatalystApp Driver Config ${GENERATOR}. Written against Catalyst ${LIBRARY.version} (FrcCatalyst`);
  L.push(`// ${LIBRARY.commit}, WPILib ${LIBRARY.wpilib}); every call it makes also exists in Catalyst 2.0.0-beta.1.`);
  L.push("//");
  L.push("// Connect it once. Driver Config never edits your other files, so these lines are yours to add:");
  if (hasRobot) {
    L.push(`//   in ${t.robotClass}, a field:        final ${cls} driverConfig = new ${cls}(this);`);
    if (t.swerveField) L.push(`//   the teleop default command:  ${t.swerveField}.setDefaultCommand(driverConfig.drive());`);
    else L.push("//   the drive command:           pass driverConfig.forward(), strafe() and turn(), deadband 0");
  } else {
    L.push(`//   where the robot is built:    final ${cls} driverConfig = new ${cls}();`);
    L.push("//   the drive command:           pass driverConfig.forward(), strafe() and turn(), deadband 0");
  }
  L.push("//   the teleop op mode, onStart: driverConfig.bind();");
  L.push("//   robotPeriodic:               driverConfig.periodic();");
  blank();

  if (hasRobot) {
    L.push("/** The robot whose commands the buttons run. Only bind() reads it, never the constructor. */");
    L.push(`private final ${t.robotClass} robot;`);
    blank();
  }

  const ports = [...new Set(c.profiles.map((p) => p.controller.port))].sort((a, b) => a - b);
  const op = c.operator;
  const allPorts = op && !ports.includes(op.port) ? [...ports, op.port].sort((a, b) => a - b) : ports;
  L.push("/** One object per Driver Station port, shared by every profile that uses the port. */");
  for (const port of allPorts) {
    const note = op && port === op.port ? (ports.includes(port) ? " // also the operator's" : " // the operator's: rumble only") : "";
    L.push(`private final CommandGenericHID port${port} = new CommandGenericHID(${port});${note}`);
  }
  blank();
  L.push("private final Profile[] profiles;");
  L.push("private Profile active;");
  L.push("private boolean slowHeld;");
  L.push("private boolean turboHeld;");
  L.push("private double lastForward;");
  L.push("private double lastStrafe;");
  L.push("private double lastTurn;");
  L.push("private final Set<String> warned = new HashSet<>();");
  blank();
  L.push("// The dashboard's driver picker: a \"String Chooser\" table, the shape Elastic, Glass and");
  L.push("// Shuffleboard draw as a drop-down. Plain NetworkTables topics, because WPILib alpha-7 removed the");
  L.push("// chooser class; the same topics work on alpha-6 and alpha-7.");
  L.push("private static final String CHOOSER = \"/SmartDashboard/Driver Profile/\";");
  L.push("private final StringPublisher chooserType = NetworkTableInstance.getDefault().getStringTopic(CHOOSER + \".type\").publish();");
  L.push("private final StringArrayPublisher chooserOptions = NetworkTableInstance.getDefault().getStringArrayTopic(CHOOSER + \"options\").publish();");
  L.push("private final StringPublisher chooserDefault = NetworkTableInstance.getDefault().getStringTopic(CHOOSER + \"default\").publish();");
  L.push("private final StringPublisher chooserActive = NetworkTableInstance.getDefault().getStringTopic(CHOOSER + \"active\").publish();");
  L.push("private final StringSubscriber chooserSelected = NetworkTableInstance.getDefault().getStringTopic(CHOOSER + \"selected\").subscribe(\"\");");
  blank();

  // --- constructor
  L.push(hasRobot ? `public ${cls}(${t.robotClass} robot) {` : `public ${cls}() {`);
  if (hasRobot) L.push("    this.robot = robot;");
  L.push("    profiles = new Profile[] {");
  c.profiles.forEach((p, i) => {
    const lay = layoutOf(c, p.controller.type);
    const byRole = (r) => p.axes.find((a) => a.role === r);
    const extra = p.axes.filter((a) => !DRIVE_ROLES.includes(a.role));
    const wantsRumble = p.rumble.some((r) => r.channel === "DRIVER" || r.channel === "BOTH");
    const opRef = op ? `port${op.port}` : "null";
    L.push(`        // ${commentSafe(p.name)}: ${lay ? lay.label : p.controller.type} on port ${p.controller.port}${p.name === c.defaultProfile ? ", the default" : ""}`);
    L.push(`        new Profile(${javaString(p.name)}, ${p.controller.port}, port${p.controller.port}, ${opRef}, ${wantsRumble},`);
    for (const r of DRIVE_ROLES) {
      const a = byRole(r);
      L.push(`                ${a ? axisExpr(a, p.speed) : "null"},${a ? ` // ${roleLabel(r)}` : ` // no ${roleLabel(r).toLowerCase()} axis`}`);
    }
    L.push(`                new Axis[] {${extra.length ? "" : "}),"}`);
    if (extra.length) {
      extra.forEach((a, k) => L.push(`                    ${axisExpr(a, p.speed)}${k < extra.length - 1 ? "," : ""}`));
      L.push(`                })${i < c.profiles.length - 1 ? "," : ""}`);
    } else if (i === c.profiles.length - 1) {
      L[L.length - 1] = L[L.length - 1].replace(/\),$/, ")");
    }
  });
  L.push("    };");
  const def = Math.max(0, c.profiles.findIndex((p) => p.name === c.defaultProfile));
  L.push(`    active = profiles[${def}];`);
  L.push("    chooserType.set(\"String Chooser\");");
  L.push(`    chooserOptions.set(new String[] {${c.profiles.map((p) => javaString(p.name)).join(", ")}});`);
  L.push("    chooserDefault.set(active.name);");
  L.push("    chooserActive.set(active.name);");
  L.push("}");
  blank();

  // --- the sticks
  L.push("/** Forward and back, as a share of top speed: + drives away from the driver. */");
  L.push("public DoubleSupplier forward() {");
  L.push("    return () -> lastForward = read(active, active.forward, true);");
  L.push("}");
  blank();
  L.push("/** Sideways, as a share of top speed: + drives to the driver's left. */");
  L.push("public DoubleSupplier strafe() {");
  L.push("    return () -> lastStrafe = read(active, active.strafe, true);");
  L.push("}");
  blank();
  L.push("/** Turning, as a share of top rotation speed: + turns counter-clockwise. */");
  L.push("public DoubleSupplier turn() {");
  L.push("    return () -> lastTurn = read(active, active.turn, true);");
  L.push("}");
  blank();
  L.push("/** An extra axis a profile names. Reads 0 while the active profile has no axis by that name. */");
  L.push("public DoubleSupplier axis(String role) {");
  L.push("    return () -> {");
  L.push("        for (Axis a : active.extra) {");
  L.push("            if (a.role.equals(role)) {");
  L.push("                return read(active, a, false);");
  L.push("            }");
  L.push("        }");
  L.push("        return 0.0;");
  L.push("    };");
  L.push("}");
  blank();
  if (hasRobot && t.swerveField) {
    L.push("/** The teleop drive command: advancedDrive with these sticks. Deadband 0, because the profile applied it. */");
    L.push("public CatalystCommand drive() {");
    L.push(`    return robot.${t.swerveField}.advancedDrive(forward(), strafe(), turn(), 0.0).withName("Driver Config drive");`);
    L.push("}");
    blank();
    L.push("/**");
    L.push(" * Field-centric forward, reseeded for this alliance: 0 degrees on Blue, 180 on Red. Catalyst's");
    L.push(" * resetHeading() seeds 0 on both, and on Red that makes the robot's back its forward.");
    L.push(" */");
    L.push("public void reseedHeading() {");
    L.push(`    robot.${t.swerveField}.resetPose(new Pose2d(robot.${t.swerveField}.getPose().getTranslation(),`);
    L.push("            AllianceFlipUtil.shouldFlip() ? Rotation2d.fromDegrees(180) : new Rotation2d()));");
    L.push("}");
    blank();
  }
  L.push("/** The name of the profile driving now. */");
  L.push("public String activeProfile() {");
  L.push("    return active.name;");
  L.push("}");
  blank();
  L.push("public boolean isSlowMode() {");
  L.push("    return slowHeld;");
  L.push("}");
  blank();
  L.push("public boolean isTurbo() {");
  L.push("    return turboHeld && !slowHeld;");
  L.push("}");
  blank();

  // --- bind()
  L.push("/**");
  L.push(" * Every profile's buttons and rumble rules. Call it from the teleop op mode's onStart: bindings");
  L.push(" * made there belong to the op mode and end with it. Only the active profile's bindings fire.");
  L.push(" */");
  L.push("public void bind() {");
  c.profiles.forEach((p, i) => {
    const lay = layoutOf(c, p.controller.type);
    L.push(`    { // ${commentSafe(p.name)}`);
    L.push(`        Profile p = profiles[${i}];`);
    L.push("        Trigger on = new Trigger(() -> active == p);");
    for (const b of p.bindings) {
      const measured = b.input.kind === "pov" ? "" : isMeasured(lay, b.input.kind, b.input.index) ? " (measured)" : lay && lay.known ? "" : " (assumed)";
      L.push(`        // ${commentSafe(inputLabel(lay, b.input))}${measured}, ${WHEN[b.when].label}: ${commentSafe(actionLabel(b.action))}`);
      L.push(`        ${inputExpr(b.input)}.and(on).${WHEN[b.when].java}(${actionExpr(b.action, hasRobot, t.swerveField)});`);
    }
    for (const r of p.rumble) {
      if (!RUMBLE_PATTERNS[r.pattern]) throw new Error(`not a rumble pattern: ${r.pattern}`);
      L.push(`        // Rumble when ${commentSafe(eventLabel(r.event, lay))}: ${RUMBLE_PATTERNS[r.pattern].label.toLowerCase()}, ${r.channel.toLowerCase()}`);
      L.push(`        p.rumble.onTrigger(${eventExpr(r.event, hasRobot)}.and(on), RumbleEvents.Pattern.${r.pattern}, RumbleEvents.Channel.${r.channel});`);
    }
    if (!p.bindings.length && !p.rumble.length) L.push("        // No buttons or rumble in this profile.");
    L.push("    }");
  });
  L.push("}");
  blank();

  // --- periodic()
  L.push("/**");
  L.push(" * Every loop, enabled or not, from robotPeriodic. Runs the active profile's rumble, follows the");
  L.push(" * dashboard's driver pick - only while disabled, so nobody's sticks change mid-match - and");
  L.push(" * publishes what the sticks are sending under /Catalyst/DriverConfig.");
  L.push(" */");
  L.push("public void periodic() {");
  L.push("    String want = chooserSelected.get();");
  L.push("    String pending = \"\";");
  L.push("    if (want != null && !want.isEmpty() && !want.equals(active.name)) {");
  L.push("        Profile next = find(want);");
  L.push("        if (next == null) {");
  L.push("            warnOnce(\"unknown:\" + want, \"the dashboard picked driver profile \\\"\" + want + \"\\\", which this code does not have\");");
  L.push("        } else if (frc.lib.catalyst.util.RobotState.isDisabled()) {");
  L.push("            active.rumble.clear();");
  L.push("            active = next;");
  L.push("            slowHeld = false;");
  L.push("            turboHeld = false;");
  L.push("            chooserActive.set(active.name);");
  L.push("        } else {");
  L.push("            pending = want;");
  L.push("        }");
  L.push("    }");
  L.push("    active.rumble.update();");
  L.push("    if (active.wantsRumble && !active.rumbleChecked && active.controller.isConnected()) {");
  L.push("        active.rumbleChecked = true;");
  L.push("        if (!active.controller.getHID().getSupportedOutputs().contains(GenericHID.SupportedOutput.RUMBLE)) {");
  L.push("            warnOnce(\"rumble:\" + active.name, active.name + \": the Driver Station says the controller on port \" + active.port");
  L.push("                    + \" cannot rumble, so this profile's rumble rules do nothing\");");
  L.push("        }");
  L.push("    }");
  L.push("    CatalystLog.log(\"DriverConfig/Profile\", active.name);");
  L.push("    CatalystLog.log(\"DriverConfig/Pending\", pending);");
  L.push("    CatalystLog.log(\"DriverConfig/Mode\", slowHeld ? \"slow\" : turboHeld ? \"turbo\" : \"normal\");");
  L.push("    CatalystLog.log(\"DriverConfig/Sticks\", new double[] {lastForward, lastStrafe, lastTurn});");
  L.push("}");
  blank();

  // --- internals
  L.push("private double read(Profile p, Axis a, boolean driveAxis) {");
  L.push("    if (a == null) {");
  L.push("        return 0.0;");
  L.push("    }");
  L.push("    double raw;");
  L.push("    try {");
  L.push("        raw = p.controller.getRawAxis(a.index);");
  L.push("    } catch (RuntimeException e) {");
  L.push("        warnOnce(\"axis:\" + p.port + \":\" + a.index, p.name + \": the controller on port \" + p.port + \" has no axis \"");
  L.push("                + a.index + \", so \" + a.role + \" reads 0 - check the controller type in Driver Config\");");
  L.push("        raw = 0.0;");
  L.push("    }");
  L.push("    if (a.invert) {");
  L.push("        raw = -raw;");
  L.push("    }");
  L.push("    double v;");
  L.push("    if (driveAxis && turboHeld && !slowHeld) {");
  L.push("        v = a.turbo.apply(raw);");
  L.push("    } else {");
  L.push("        if (driveAxis && slowHeld) {");
  L.push("            a.normal.engageSlowMode();");
  L.push("        } else {");
  L.push("            a.normal.disengageSlowMode();");
  L.push("        }");
  L.push("        v = a.normal.apply(raw);");
  L.push("    }");
  L.push("    return a.slew == null ? v : a.slew.calculate(v);");
  L.push("}");
  blank();
  L.push("private Profile find(String name) {");
  L.push("    for (Profile p : profiles) {");
  L.push("        if (p.name.equals(name)) {");
  L.push("            return p;");
  L.push("        }");
  L.push("    }");
  L.push("    return null;");
  L.push("}");
  blank();
  L.push("private void warnOnce(String key, String message) {");
  L.push("    if (warned.add(key)) {");
  L.push("        DriverStationErrors.reportWarning(\"[DriverConfig] \" + message, false);");
  L.push("    }");
  L.push("}");
  blank();
  L.push("/** One driver's settings. */");
  L.push("private static final class Profile {");
  L.push("    final String name;");
  L.push("    final int port;");
  L.push("    final CommandGenericHID controller;");
  L.push("    final RumbleEvents rumble;");
  L.push("    final boolean wantsRumble;");
  L.push("    final Axis forward;");
  L.push("    final Axis strafe;");
  L.push("    final Axis turn;");
  L.push("    final Axis[] extra;");
  L.push("    boolean rumbleChecked;");
  blank();
  L.push("    Profile(String name, int port, CommandGenericHID controller, CommandGenericHID operator, boolean wantsRumble,");
  L.push("            Axis forward, Axis strafe, Axis turn, Axis[] extra) {");
  L.push("        this.name = name;");
  L.push("        this.port = port;");
  L.push("        this.controller = controller;");
  L.push("        this.rumble = new RumbleEvents(controller.getHID(), operator == null ? null : operator.getHID());");
  L.push("        this.wantsRumble = wantsRumble;");
  L.push("        this.forward = forward;");
  L.push("        this.strafe = strafe;");
  L.push("        this.turn = turn;");
  L.push("        this.extra = extra;");
  L.push("    }");
  L.push("}");
  blank();
  L.push("/**");
  L.push(" * One stick axis: the raw index, which way it goes, and the library's DriverProfile shaping -");
  L.push(" * deadband, curve, and a cap per speed mode. Turbo is a second DriverProfile, because a");
  L.push(" * DriverProfile has one cap and a slow mode but no turbo.");
  L.push(" */");
  L.push("private static final class Axis {");
  L.push("    final String role;");
  L.push("    final int index;");
  L.push("    final boolean invert;");
  L.push("    final DriverProfile normal;");
  L.push("    final DriverProfile turbo;");
  L.push("    final SlewRateLimiter slew;");
  blank();
  L.push("    Axis(String role, int index, boolean invert, double deadband, DriverProfile.Curve curve,");
  L.push("            double cap, double slowMultiplier, double turboCap, double slewSeconds) {");
  L.push("        this.role = role;");
  L.push("        this.index = index;");
  L.push("        this.invert = invert;");
  L.push("        this.normal = DriverProfile.builder().deadband(deadband).curve(curve).maxSpeed(cap).slowMode(slowMultiplier).build();");
  L.push("        this.turbo = DriverProfile.builder().deadband(deadband).curve(curve).maxSpeed(turboCap).build();");
  L.push("        this.slew = slewSeconds > 0 ? new SlewRateLimiter(1.0 / slewSeconds) : null;");
  L.push("    }");
  L.push("}");
  return L;
}

export function bodyBlock(config, indent = "    ") {
  const c = normalize(config);
  return [
    indent + MARK.bodyBegin,
    ...bodyLines(c).map((l) => (l ? indent + l : "")),
    indent + MARK.bodyEnd,
  ];
}

// ------------------------------------------------------------------ the constants block
//
// For robot code that builds its own DriverProfile from a block of constants - X1Constants.Driving,
// with DEADBAND, MAX_SPEED and DEFAULT_CURVE - Driver Config can own that block instead of, or as
// well as, writing a whole class. The team puts the two CONSTANTS marker lines around the block
// once; after that the app replaces what is between them and nothing else. It never adds the
// markers itself: that would be editing outside a region.

function constantsLines(c) {
  const k = c.target.constants;
  const p = c.profiles.find((x) => x.name === c.defaultProfile) || c.profiles[0];
  if (!k || !p) throw new Error("a constants block needs a target and a profile");
  const role = (r) => p.axes.find((a) => a.role === r);
  const lead = role("forward") || role("strafe") || role("turn") || p.axes[0];
  if (!lead) throw new Error(`${p.name} has no axes to take the feel from`);
  const curve = CURVES[lead.curve];
  if (!curve) throw new Error(`not a curve: ${lead.curve}`);
  const turn = role("turn");
  const L = [];
  L.push(JSON_BEGIN);
  for (const line of embeddedJson(c)) L.push(" * " + line);
  L.push(" */");
  L.push(`// Generator: CatalystApp Driver Config ${GENERATOR}. The default profile as constants, for code that builds`);
  L.push(`// its own DriverProfile. Written against Catalyst ${LIBRARY.version} (FrcCatalyst ${LIBRARY.commit}).`);
  L.push(`/** Driver feel from CatalystApp's Driver Config: the "${commentSafe(p.name)}" profile. Change it in the app. */`);
  L.push(`public static final class ${k.className} {`);
  L.push(`    private ${k.className}() {}`);
  L.push("");
  const constant = (doc, decl) => {
    L.push(`    /** ${doc} */`);
    L.push(`    public static final ${decl};`);
  };
  constant("Stick deadband, for DriverProfile.Builder.deadband (WPILib MathUtil.applyDeadband).", `double DEADBAND = ${javaNumber(lead.deadband)}`);
  constant("Share of top speed with no button held, for DriverProfile.Builder.maxSpeed.", `double MAX_SPEED = ${javaNumber(p.speed.max)}`);
  constant("Response curve, for DriverProfile.Builder.curve.",
    `frc.lib.catalyst.util.DriverProfile.Curve DEFAULT_CURVE = frc.lib.catalyst.util.DriverProfile.Curve.${curve.java}`);
  constant("Multiplier while slow mode is held, for DriverProfile.Builder.slowMode.", `double SLOW_MODE = ${javaNumber(p.speed.slow)}`);
  constant("Multiplier on MAX_SPEED while turbo is held; nothing goes past 100%.", `double TURBO = ${javaNumber(p.speed.turbo)}`);
  constant("The turn stick's share of top rotation speed.", `double TURN_SCALE = ${javaNumber(turn ? turn.scale : 1)}`);
  constant("Seconds from stop to full stick through a SlewRateLimiter; 0 is off.", `double SLEW_SECONDS = ${javaNumber(lead.slew)}`);
  constant("Driver Station port of the driver's controller.", `int DRIVER_PORT = ${p.controller.port}`);
  for (const r of DRIVE_ROLES) {
    const a = role(r);
    const up = r.toUpperCase();
    constant(`Raw axis (getRawAxis) for ${roleLabel(r).toLowerCase()}; -1 when the profile has none.`, `int ${up}_AXIS = ${a ? a.axis : -1}`);
    constant(`Whether ${roleLabel(r).toLowerCase()} is inverted: multiply the raw axis by -1 first.`, `boolean ${up}_INVERTED = ${a ? a.invert : false}`);
  }
  L.push("}");
  return L;
}

export function constantsBlock(config, indent = "    ") {
  const c = normalize(config);
  return [
    indent + MARK.constantsBegin,
    ...constantsLines(c).map((l) => (l ? indent + l : "")),
    indent + MARK.constantsEnd,
  ];
}

/**
 * What writing the constants block into `existing` produces. A file without the markers is refused
 * with the two lines to paste, rather than having the app decide where somebody's block begins.
 */
export function planConstants(existing, config) {
  const c = normalize(config);
  const k = c.target.constants;
  if (!k) return { ok: false, problems: ["No constants block is chosen."] };
  if (existing == null) return { ok: false, problems: [`${k.path} is not in the project.`] };
  const r = findRegions(existing);
  if (r.problems.length) return { ok: false, problems: r.problems };
  if (!r.constants) {
    return {
      ok: false,
      needsMarkers: true,
      markers: [MARK.constantsBegin, MARK.constantsEnd],
      problems: [`${k.path} has no Driver Config constants region yet. Put the two marker lines around the ${k.className} class once - the first above it and its comment, the second below its closing brace. From then on the app replaces only what is between them.`],
    };
  }
  const reg = r.constants;
  const from = r.lines[reg.start].start;
  const to = r.lines[reg.end].end;
  return { ok: true, mode: "update", text: existing.slice(0, from) + constantsBlock(c, reg.indent).join(r.eol) + existing.slice(to) };
}

/** A whole new file: the package, both regions, and the class around the body. */
export function newFile(config) {
  const c = normalize(config);
  return [
    `package ${c.target.package};`,
    "",
    ...importsBlock(c),
    "",
    "/**",
    " * How each driver's controller drives this robot: sticks, deadbands, curves, speed limits, buttons",
    " * and rumble, one profile per driver.",
    " *",
    " * <p>Generated by CatalystApp (Tools, Driver Config). Change it there and press Apply to project:",
    " * the app rewrites only the two marked regions of this file and never touches what you add outside them.",
    " */",
    `public final class ${c.target.className} {`,
    ...bodyBlock(c, "    "),
    "}",
    "",
  ].join("\n");
}

// ------------------------------------------------------------------ reading a file back

function lineTable(text) {
  const lines = [];
  const re = /\r\n|\n|\r/g;
  let start = 0;
  let m;
  while ((m = re.exec(text))) {
    lines.push({ text: text.slice(start, m.index), start, end: m.index });
    start = m.index + m[0].length;
  }
  if (start < text.length) lines.push({ text: text.slice(start), start, end: text.length });
  return lines;
}

/** Where the two regions are, or why they cannot be trusted. */
export function findRegions(text) {
  const lines = lineTable(text);
  const begins = { IMPORTS: [], BODY: [], CONSTANTS: [] };
  const ends = { IMPORTS: [], BODY: [], CONSTANTS: [] };
  lines.forEach((l, i) => {
    const b = BEGIN_RE.exec(l.text);
    if (b) begins[b[2]].push({ line: i, indent: b[1] });
    const e = END_RE.exec(l.text);
    if (e) ends[e[1]].push({ line: i });
  });
  const problems = [];
  const region = (name) => {
    const bs = begins[name];
    const es = ends[name];
    if (!bs.length && !es.length) return null;
    const word = name.toLowerCase();
    if (bs.length !== 1 || es.length !== 1) {
      problems.push(`The ${word} region has ${bs.length} start marker(s) and ${es.length} end marker(s); it needs exactly one of each.`);
      return null;
    }
    if (es[0].line < bs[0].line) {
      problems.push(`The ${word} region's end marker comes before its start marker.`);
      return null;
    }
    return { start: bs[0].line, end: es[0].line, indent: bs[0].indent };
  };
  const imports = region("IMPORTS");
  const body = region("BODY");
  const constants = region("CONSTANTS");
  const present = [imports, body, constants].filter(Boolean);
  for (let i = 0; i < present.length; i++) {
    for (let j = i + 1; j < present.length; j++) {
      const a = present[i];
      const b = present[j];
      if (!(a.end < b.start || b.end < a.start)) problems.push("Two Driver Config regions overlap.");
    }
  }
  const eol = (text.match(/\r\n|\n|\r/) || ["\n"])[0];
  return { lines, imports, body, constants, problems, eol };
}

function regionText(lines, r) {
  return lines.slice(r.start, r.end + 1).map((l) => l.text.replace(/\s+$/, ""));
}

const sameLines = (a, b) => a.length === b.length && a.every((l, i) => l === b[i]);

/**
 * Read a generated file back: the profile it carries, and whether the code in its regions is still
 * what that profile generates. `handEdited` is only claimed when the file came from this same
 * generator - an older generator writing different code is not somebody's hand edit.
 */
export function readJava(text) {
  const r = findRegions(text);
  const reg = r.body || r.constants;
  if (!reg) return { found: false, problems: r.problems };
  const kind = r.body ? "BODY" : "CONSTANTS";
  const inner = r.lines.slice(reg.start + 1, reg.end).map((l) => l.text);
  const at = inner.findIndex((l) => l.trim() === JSON_BEGIN);
  if (at < 0) return { found: true, region: kind, problems: [...r.problems, "The generated region has no profile block, so it cannot be read back."] };
  const json = [];
  let closed = false;
  for (let i = at + 1; i < inner.length; i++) {
    if (/^\s*\*\/\s*$/.test(inner[i])) { closed = true; break; }
    json.push(inner[i].replace(/^\s*\* ?/, ""));
  }
  if (!closed) return { found: true, region: kind, problems: [...r.problems, "The profile block in the generated region is not closed."] };
  let config;
  try {
    config = parseConfig(json.join("\n"));
  } catch (e) {
    return { found: true, region: kind, problems: [...r.problems, `The profile block could not be read: ${e.message}.`] };
  }
  const gm = inner.join("\n").match(/Generator: CatalystApp Driver Config (\d+)/);
  const generator = gm ? Number(gm[1]) : null;
  let handEdited = false;
  if (generator === GENERATOR) {
    try {
      const strip = (l) => l.replace(/\s+$/, "");
      if (kind === "BODY") {
        const bodySame = sameLines(regionText(r.lines, r.body), bodyBlock(config, r.body.indent).map(strip));
        const importsSame = !r.imports || sameLines(regionText(r.lines, r.imports), importsBlock(config));
        handEdited = !(bodySame && importsSame);
      } else {
        handEdited = !sameLines(regionText(r.lines, r.constants), constantsBlock(config, r.constants.indent).map(strip));
      }
    } catch {
      handEdited = true;
    }
  }
  return { found: true, region: kind, config, problems: r.problems, generator, handEdited };
}

/**
 * What writing `config` into a file that currently reads `existing` (null: no file) produces.
 * Refuses a file that has no regions - it is somebody's own class that happens to share the name -
 * and a file whose markers are broken, rather than guessing where a region begins.
 */
export function planWrite(existing, config) {
  const c = normalize(config);
  if (existing == null) return { ok: true, mode: "create", text: newFile(c) };
  const r = findRegions(existing);
  if (r.problems.length) return { ok: false, problems: r.problems };
  if (!r.imports || !r.body) {
    return {
      ok: false,
      problems: [!r.imports && !r.body
        ? "This file exists and has no Driver Config regions, so it is not one this app wrote. Rename it, or choose another class name."
        : `This file has a Driver Config ${r.body ? "body" : "imports"} region but no ${r.body ? "imports" : "body"} region. Put the missing markers back, or delete the file so the app can create it again.`],
    };
  }
  const reps = [
    { r: r.imports, lines: importsBlock(c) },
    { r: r.body, lines: bodyBlock(c, r.body.indent) },
  ].sort((a, b) => b.r.start - a.r.start);
  let text = existing;
  for (const { r: reg, lines } of reps) {
    const from = r.lines[reg.start].start;
    const to = r.lines[reg.end].end;
    text = text.slice(0, from) + lines.join(r.eol) + text.slice(to);
  }
  return { ok: true, mode: "update", text };
}
